# Generated by Django 4.0.4 on 2022-04-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_destination_slugfield_cruise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cruise',
        ),
    ]
