# Generated by Django 4.0.4 on 2022-04-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0003_delete_cruise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='SlugField',
        ),
    ]
