# Generated by Django 4.0.4 on 2022-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_remove_destination_slugfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='SlugField',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
    ]
